# Run docker-compose build
# Run docker-compose up
# Live long and prosper

version: '3'
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
    networks:
      - internal
    volumes:
     - ./nginx/image-files/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - mysql
      - api
      - web
    ports:
      - 81:80
      - 444:443

  api:
    container_name: api
    build:
      context: ./api
      args:
        TIMEZONE: ${APP_TIME_ZONE} 
    depends_on:
      - mysql
    networks:
      - internal
    env_file:
      - .env

  web:
    container_name: web
    build:
      context: ./web
      # dockerfile: ./Dockerfile.dev       # For development
      dockerfile: ./Dockerfile       # For production
    depends_on:
      - api
    networks:
      - internal

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    networks:
      - internal
    env_file:
      - .env
    ports:
      - 3306:3306
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - mysql_data:/var/lib/mysql

networks:
  internal:
    driver: bridge

volumes:
  mysql_data: